### ISSUE TITLE
Empty meta file(`snapshot-xxx-yyy.zip.meta`) disturbs snapshot downloading

### ISSUE THREAD

**Issue by longfin** [planetarium/9c-launcher#1035]
When there are empty meta-files that exist, the launcher will fail to download snapshots with the following logs. (I don't know why empty meta-files exist).

```
[2021-11-09 14:38:57.076] [info]  Downloading snapshot.
[2021-11-09 14:38:57.076] [info]  [
  { BlockEpoch: 18940, TxEpoch: 18940 },
  { BlockEpoch: 18939, TxEpoch: 18939 },
  { BlockEpoch: 18938, TxEpoch: 18938 },
  { BlockEpoch: 18937, TxEpoch: 18937 }
]
[2021-11-09 14:38:57.081] [info]  download snapshot path: https://snapshots.nine-chronicles.com/main/partition/snapshot-18940-18940.zip
[2021-11-09 14:38:57.083] [info]  download snapshot path: https://snapshots.nine-chronicles.com/main/partition/snapshot-18939-18939.zip
[2021-11-09 14:38:57.086] [info]  download snapshot path: https://snapshots.nine-chronicles.com/main/partition/snapshot-18938-18938.zip
[2021-11-09 14:38:57.089] [info]  download snapshot path: https://snapshots.nine-chronicles.com/main/partition/snapshot-18937-18937.zip
[2021-11-09 14:38:57.090] [error] Download failed:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at he (C:\Users\Ninec\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:2:287675)
    at C:\Users\Ninec\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:2:291879
    at Array.map (<anonymous>)
    at Se (C:\Users\Ninec\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:2:291731)
    at Module.Re (C:\Users\Ninec\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:2:293562)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Kt (C:\Users\Ninec\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:2:323072)
```

**Comment by BasixKOR** [comment]
Note to self: Disable partial behaviour if meta is invalid
