### ISSUE TITLE
Failed to send and swap forever without alerts

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#1139]
## Situtation

I got this report from the Discord community server.

He failed to send and swap but there was no error notification even reinstall game multiple times and had tried to swap and send multiple times over one week.

And I got his logs and I could find the lines.

```
[2022-01-03 15:15:59.290] [error] Error: Command failed: .\NineChronicles.Headless.Executable action transfer-asset <SOME ADDRESS> <SOME ADDRESS> 1 path\to\localappdata\Temp\tmp-7752-clUkIiHCUnIo BreakShadow test 
System.IO.DirectoryNotFoundException: Could not find a part of the path 'path\to\localappdata\Temp\tmp-7752-clUkIiHCUnIo'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at NineChronicles.Headless.Executable.Commands.ActionCommand.TransferAsset(String senderAddress, String recipientAddress, String amount, String filePath, String memo) in C:\Users\circleci\project\NineChronicles.Headless\NineChronicles.Headless.Executable\Commands\ActionCommand.cs:line 156

    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at func (electron/js2c/asar.js:140:31)
    at li.execSync (path\to\localappdata\Programs\Nine Chronicles\resources\app\main.js:357:24608)
    at li.TransferAsset (path\to\localappdata\Programs\Nine Chronicles\resources\app\main.js:357:26760)
    at IpcMainImpl.<anonymous> (path\to\localappdata\Programs\Nine Chronicles\resources\app\main.js:357:28213)
    at IpcMainImpl.emit (events.js:223:5)
    at IpcMainImpl.EventEmitter.emit (domain.js:475:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8837)
    at WebContents.emit (events.js:223:5)
```

## Reason

Though I masked its full path, he used `'`, single comma in his Windows username. Node.js' `tmp` module removes all quotes `"` and `'`.

https://github.com/raszi/node-tmp/blob/7e96f4d1546a6a1d8d7d73da20206e242b4b8a8f/lib/tmp.js#L570-L575

## Expectation (just my thought)

- [ ] Alert to user if the error occurred.
- [ ] Fix `tmp` modules and bump, or `patch-packages` (?).

**Comment by Akamig** [comment]
We don't use headless for swap and send assets anymore, so closing.
