### ISSUE TITLE
맥에서 마이너 옵션을 킬 시 헤드리스가 실행 안 되는 문제

### ISSUE THREAD

**Issue by riemannulus** [planetarium/9c-launcher#15]
## AS-IS
```
System.IO.IOException: Read-only file system
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Libplanet.Store.DefaultStore..ctor(String path, Boolean compress, Boolean journal, Int32 indexCacheSize, Int32 blockCacheSize, Int32 txCacheSize, Int32 statesCacheSize, Boolean flush, Boolean readOnly)
   at Libplanet.Standalone.Hosting.LibplanetNodeService`1.LoadStore(String path, String type, Int32 statesCacheSize) in /Users/suho/Workspaces/nekoyume-unity/Libplanet.Standalone/Hosting/LibplanetNodeService.cs:line 171
   at Libplanet.Standalone.Hosting.LibplanetNodeService`1..ctor(LibplanetNodeServiceProperties`1 properties, IBlockPolicy`1 blockPolicy, Func`5 minerLoopAction, Progress`1 preloadProgress, Boolean ignoreBootstrapFailure) in /Users/suho/Workspaces/nekoyume-unity/Libplanet.Standalone/Hosting/LibplanetNodeService.cs:line 63
   at NineChronicles.Standalone.NineChroniclesNodeService..ctor(LibplanetNodeServiceProperties`1 properties, Nullable`1 rpcNodeServiceProperties, Progress`1 preloadProgress, Boolean ignoreBootstrapFailure) in /Users/suho/Workspaces/nekoyume-unity/NineChronicles.Standalone/NineChroniclesNodeService.cs:line 85
   at NineChronicles.Standalone.StandaloneServices.RunHeadlessAsync(NineChroniclesNodeServiceProperties properties, IHostBuilder hostBuilder, StandaloneContext standaloneContext, CancellationToken cancellationToken) in /Users/suho/Workspaces/nekoyume-unity/NineChronicles.Standalone/StandaloneServices.cs:line 18
   at NineChronicles.Standalone.Controllers.GraphQLController.RunStandAlone(ServiceBindingProperties properties) in /Users/suho/Workspaces/nekoyume-unity/NineChronicles.Standalone/Controllers/GraphQLController.cs:line 77
```
스탠드얼론에서 발생하는 이슈입니다. NoMiner 옵션을 false로 하면 해당 이슈가 발생합니다.

# TO-BE
고칩시다

**Comment by Akamig** [comment]
We solved this issue, closing.
