### ISSUE TITLE
Launcher development environment not working on linux

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#1730]
```
> yarn dev:v2
[1] 
[1] ##
[1] ## BUILDING BUNDLE FOR: main process
[1] ## CONFIGURATION: development
[1] ## VERSION: 0.1.0
[1] ##
[1] 
[0] 
[0] ##
[0] ## BUILDING BUNDLE FOR: render process
[0] ## CONFIGURATION: development
[0] ## VERSION: 0.1.0
[0] ##
[0] 
[0] (node:4702) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] ℹ ｢wds｣: Project is running at http://localhost:9000/
[0] ℹ ｢wds｣: webpack output is served from /
[0] ℹ ｢wds｣: Content not from webpack is served from /home/lumomig/code/scratchpad/9c-launcher/dist
[0] ℹ ｢wds｣: 404s will fallback to /index.html
[1] assets by chunk 1.71 MiB (auxiliary name: main)
[1]   asset c632a83a490a0d127e26631c66e2d287.node 336 KiB [compared for emit] (auxiliary name: main)
[1]   asset f7b57981f8728698d390baa3921158b4.node 311 KiB [compared for emit] (auxiliary name: main)
[1]   asset 456404ce70f569237b7e5924a6822845.node 297 KiB [compared for emit] (auxiliary name: main)
[1]   asset 36c6e317b27d9041cdb3dbd79dc3ed66.node 288 KiB [compared for emit] (auxiliary name: main)
[1]   asset 3ede09701f250943941a2d5fa4ef6d03.node 243 KiB [compared for emit] (auxiliary name: main)
[1]   asset 8ce97eddd14f8fa8a05dd224290a236b.node 224 KiB [compared for emit] (auxiliary name: main)
[1]   asset 3022d7da48305db1a1651a729c30991e.png 55 KiB [compared for emit] (auxiliary name: main)
[1] assets by status 4.01 MiB [emitted]
[1]   asset main.js 4 MiB [emitted] [compared for emit] (name: main) 1 related asset
[1]   asset package.json 9.21 KiB [emitted] [compared for emit] [from: ../package.json] [copied]
[1] asset preload.js 185 bytes [compared for emit] (name: preload)
[1] orphan modules 507 KiB [orphan] 130 modules
[1] runtime modules 1.4 KiB 7 modules
[1] modules by path ../node_modules/ 3.09 MiB
[1]   javascript modules 2.87 MiB
[1]     cacheable modules 2.87 MiB 827 modules
[1]     2 modules
[1]   json modules 226 KiB 13 modules
[1] modules by path ./ 115 KiB 38 modules
[1] 25 modules
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 31:28-76
[1] Module not found: Error: Can't resolve './check-free-space.android-arm64.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 43:28-79
[1] Module not found: Error: Can't resolve './check-free-space.android-arm-eabi.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 63:28-77
[1] Module not found: Error: Can't resolve './check-free-space.win32-x64-msvc.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 77:28-78
[1] Module not found: Error: Can't resolve './check-free-space.win32-ia32-msvc.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 91:28-79
[1] Module not found: Error: Can't resolve './check-free-space.win32-arm64-msvc.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 109:28-73
[1] Module not found: Error: Can't resolve './check-free-space.darwin-x64.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 123:28-75
[1] Module not found: Error: Can't resolve './check-free-space.darwin-arm64.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 142:24-70
[1] Module not found: Error: Can't resolve './check-free-space.freebsd-x64.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 159:30-79
[1] Module not found: Error: Can't resolve './check-free-space.linux-x64-musl.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 172:30-78
[1] Module not found: Error: Can't resolve './check-free-space.linux-x64-gnu.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 188:30-81
[1] Module not found: Error: Can't resolve './check-free-space.linux-arm64-musl.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 201:30-80
[1] Module not found: Error: Can't resolve './check-free-space.linux-arm64-gnu.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ../node_modules/@planetarium/check-free-space/index.js 216:28-82
[1] Module not found: Error: Can't resolve './check-free-space.linux-arm-gnueabihf.node' in '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@planetarium/check-free-space'
[1]  @ ./main/main.ts 110:0-61 509:38-50
[1] 
[1] WARNING in ./preload/sentry.ts 17:15-22
[1] Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)
[1]  @ ./main/main.ts 88:0-53 116:0-16
[1] 
[1] 20 warnings have detailed information that is not shown.
[1] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
[1] 
[1] webpack 5.40.0 compiled with 14 warnings in 5473 ms
[1] (node:4696) [DEP_WEBPACK_STATS_WARNINGS_FILTER] DeprecationWarning: config.stats.warningsFilter is deprecated in favor of config.ignoreWarnings
[1] (Use `node --trace-deprecation ...` to show where the warning was created)
[1] Sentry is disabled in development mode.
[1] 11:28:00.457 › initializeApp
[1] 11:28:00.741 › (node:4778) ExtensionLoadWarning: Warnings loading extension at /home/lumomig/.config/Nine Chronicles/extensions/pfgnfdagidkfgccljigdamigbcnndkod:
[1]   Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
[1]   Permission 'contextMenus' is unknown or URL pattern is malformed.
[1] 
[1] (Use `electron --trace-warnings ...` to show where the warning was created)
[1] 11:28:00.743 › (node:4778) ExtensionLoadWarning: Warnings loading extension at /home/lumomig/.config/Nine Chronicles/extensions/jdkknkkbebbapilgoeccciglkfbmbnfm:
[1]   Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
[1] 
[1] 11:28:00.743 › Added Extension:  Apollo Client Devtools
[1] [4778:0810/112800.922534:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[1] [4825:0810/112800.923937:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0] ℹ ｢wdm｣: wait until bundle finished: /v2.html
[1] 11:28:01.361 › APVs are different, ignore. (local: undefined, remote: 100260/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQCG2yQNyXu3ovuUBNMEQiqx1vdo.FCMet9FoayFiIL89QIgXGRTU84nrcmLL4ud2j9ogrGt7ScmqaD97N.4rrtraXE=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTU2Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS92MTAwMjYwL1dpbmRvd3MuemlwdTk6dGltZXN0YW1wdTEwOjIwMjItMDctMjhl)
[0] ⚠ ｢wdm｣: assets by path assets/*.png 34.7 MiB
[0]   assets by chunk 27.6 MiB (auxiliary name: collection)
[0]     assets by chunk 33 KiB (auxiliary name: render) 2 assets
[0] assets by path *.js 25.7 MiB
[0]   assets by chunk 116 KiB (id hint: default)
[0]     asset default-config_ts-renderer_styles_font_ts-utils_ts-node_modules_webpack_hot_sync_log_.js 59.8 KiB [emitted] (id hint: default)
[0]     asset default-collection_common_utils_ts-preload_sentry_ts-renderer_i18n_index_tsx-renderer_stores_-808019.js 56.7 KiB [emitted] (id hint: default)
[0]   6 assets
[0] assets by path *.html 2.86 KiB
[0]   asset index.html 859 bytes [emitted]
[0]   asset v2.html 736 bytes [emitted]
[0]   asset transfer.html 727 bytes [emitted]
[0]   asset collection.html 610 bytes [emitted]
[0] asset assets/e2d60bc49517598c0ce8.ttf 237 KiB [emitted] [immutable] [from: renderer/resources/Montserrat.ttf] (auxiliary id hint: default)
[0] asset assets/c17ca33e296d68361907.gif 15.1 KiB [emitted] [immutable] [from: v2/resources/collection/select-arrow.gif] (auxiliary name: v2)
[0] Entrypoint render 23.5 MiB (4.74 MiB) = vendors.js 21.7 MiB graphql.js 717 KiB default-config_ts-renderer_styles_font_ts-utils_ts-node_modules_webpack_hot_sync_log_.js 59.8 KiB default-collection_common_utils_ts-preload_sentry_ts-renderer_i18n_index_tsx-renderer_stores_-808019.js 56.7 KiB render.js 957 KiB 9 auxiliary assets
[0] Entrypoint collection 23.1 MiB (27.6 MiB) = vendors.js 21.7 MiB graphql.js 717 KiB collection.js 673 KiB 26 auxiliary assets
[0] Entrypoint transfer 22.7 MiB (237 KiB) = vendors.js 21.7 MiB graphql.js 717 KiB default-config_ts-renderer_styles_font_ts-utils_ts-node_modules_webpack_hot_sync_log_.js 59.8 KiB transfer.js 260 KiB 1 auxiliary asset
[0] Entrypoint v2 23.8 MiB (3.31 MiB) = vendors.js 21.7 MiB graphql.js 717 KiB default-collection_common_utils_ts-preload_sentry_ts-renderer_i18n_index_tsx-renderer_stores_-808019.js 56.7 KiB v2.js 1.29 MiB 14 auxiliary assets
[0] orphan modules 3.99 MiB [orphan] 6009 modules
[0] runtime modules 135 KiB 72 modules
[0] built modules 8.65 MiB (javascript) 35.7 MiB (asset) [built]
[0]   modules by path ../node_modules/ 7.53 MiB
[0]     javascript modules 7.52 MiB 1377 modules
[0]     json modules 4.99 KiB
[0]       ../node_modules/conf/node_modules/ajv/dist/refs/json-schema-draft-07.json 2.72 KiB [built] [code generated]
[0]       ../node_modules/conf/node_modules/ajv/dist/refs/data.json 360 bytes [built] [code generated]
[0]       ../node_modules/axios/package.json 1.92 KiB [built] [code generated]
[0]   modules by path ./ 1.12 MiB (javascript) 35.7 MiB (asset)
[0]     javascript modules 932 KiB 219 modules
[0]     asset modules 214 KiB (javascript) 35.7 MiB (asset) 85 modules
[0] 
[0] WARNING in ../node_modules/@reach/auto-id/dist/reach-auto-id.esm.js 86:13-20
[0] export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
[0]  @ ../node_modules/@reach/alert-dialog/dist/reach-alert-dialog.esm.js 3:0-39 73:11-16
[0]  @ ./v2/views/MonsterCollectionOverlay/dialog.tsx 6:0-119 18:36-54 22:32-50 44:33-49 52:39-61 132:41-59 208:152-168
[0]  @ ./v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx 22:0-33 169:108-113 174:233-238 179:326-331 183:148-153
[0]  @ ./v2/views/MonsterCollectionOverlay/index.tsx 8:0-70 72:38-62
[0]  @ ./v2/components/core/Menu/index.tsx 20:0-77 81:39-63
[0]  @ ./v2/components/core/Layout/index.tsx 6:0-27 69:273-277
[0]  @ ./v2/views/MissingActivationView.tsx 9:0-47 56:42-48
[0]  @ ./v2/Routes.tsx 14:0-66 58:15-36
[0]  @ ./v2/App.tsx 8:0-30 22:203-209
[0]  @ ./v2/render.tsx 89:0-24 108:45-48
[0] 
[0] WARNING in ../node_modules/@reach/auto-id/dist/reach-auto-id.esm.js 88:14-21
[0] export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
[0]  @ ../node_modules/@reach/alert-dialog/dist/reach-alert-dialog.esm.js 3:0-39 73:11-16
[0]  @ ./v2/views/MonsterCollectionOverlay/dialog.tsx 6:0-119 18:36-54 22:32-50 44:33-49 52:39-61 132:41-59 208:152-168
[0]  @ ./v2/views/MonsterCollectionOverlay/MonsterCollectionContent.tsx 22:0-33 169:108-113 174:233-238 179:326-331 183:148-153
[0]  @ ./v2/views/MonsterCollectionOverlay/index.tsx 8:0-70 72:38-62
[0]  @ ./v2/components/core/Menu/index.tsx 20:0-77 81:39-63
[0]  @ ./v2/components/core/Layout/index.tsx 6:0-27 69:273-277
[0]  @ ./v2/views/MissingActivationView.tsx 9:0-47 56:42-48
[0]  @ ./v2/Routes.tsx 14:0-66 58:15-36
[0]  @ ./v2/App.tsx 8:0-30 22:203-209
[0]  @ ./v2/render.tsx 89:0-24 108:45-48
[0] 
[0] WARNING in ./preload/sentry.ts 19:15-22
[0] Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)
[0]  @ ./renderer/render.tsx 86:0-53 88:0-16
[0] 
[0] webpack 5.40.0 compiled with 3 warnings in 16225 ms
[0] ℹ ｢wdm｣: Compiled with warnings.
[1] 11:28:13.200 › [HMR] Waiting for update signal from WDS...
[1] 11:28:13.247 › [WDS] Hot Module Replacement enabled.
[1] 11:28:13.248 › [WDS] Live Reloading enabled.
[1] 11:28:13.249 › [WDS] Warnings while compiling.
[1] 11:28:13.250 › {
[1]   moduleIdentifier: '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@reach/auto-id/dist/reach-auto-id.esm.js',
[1]   moduleName: '../node_modules/@reach/auto-id/dist/reach-auto-id.esm.js',
[1]   loc: '86:13-20',
[1]   message: "export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)"
[1] }
[1] 11:28:13.252 › {
[1]   moduleIdentifier: '/home/lumomig/code/scratchpad/9c-launcher/node_modules/@reach/auto-id/dist/reach-auto-id.esm.js',
[1]   moduleName: '../node_modules/@reach/auto-id/dist/reach-auto-id.esm.js',
[1]   loc: '88:14-21',
[1]   message: "export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)"
[1] }
[1] 11:28:13.252 › {
[1]   moduleIdentifier: '/home/lumomig/code/scratchpad/9c-launcher/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[3].use!/home/lumomig/code/scratchpad/9c-launcher/src/preload/sentry.ts',
[1]   moduleName: './preload/sentry.ts',
[1]   loc: '19:15-22',
[1]   message: "Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)"
[1] }
[1] 11:28:13.288 › (node:4778) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'length')
[1]     at checkForUpdates (/home/lumomig/code/scratchpad/9c-launcher/dist/main.js:26241:17)
[1]     at App.<anonymous> (/home/lumomig/code/scratchpad/9c-launcher/dist/main.js:25158:79)
[1] 11:28:13.289 › (node:4778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1] 11:28:13.267 › Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
[1]   Policy set or a policy with "unsafe-eval" enabled. This exposes users of
[1]   this app to unnecessary security risks.
[1] 
[1] For more information and help, consult
[1] https://electronjs.org/docs/tutorial/security.
[1] This warning will not show up
[1] once the app is packaged.
[1] [4778:0810/112813.823811:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[1] [4778:0810/112813.823847:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
[1] [4778:0810/112813.829187:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[1] [4778:0810/112813.829227:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
^X^C[1] /home/lumomig/code/scratchpad/9c-launcher/node_modules/electron/dist/electron exited with signal SIGINT
[1] yarn start:v2 exited with code 1
--> Sending SIGTERM to other processes..
[0] yarn server exited with code 129
```
and the launcher itself fails to display any UI, got any leads?
![image](https://user-images.githubusercontent.com/6278999/183798440-c6d9e191-0755-498c-98ff-539ff387421b.png)

**Comment by Akamig** [comment]
I tried:
- Build headless
- Download player bundle
- yarn start:v2
- use --no-gpu, --in-process-gpu, --no-sandbox flag on electron.
- Reinstall graphics driver to nouveau

**Comment by Akamig** [comment]
However I think this is solely problem of the development environment, since just executing packed launcher was successful.
```
> ~/Downloads/artifact\(1\)/Nine\ Chronicles
Sentry is disabled by config
11:45:10.680 › initializeApp
[7169:0810/114511.076046:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
11:45:11.131 › APVs are different, ignore. (local: 100231/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEQCIDLDIgRgvwNh8Va1IU3wjVCbNTa6.KcFAtHXYCxlJ+4pAiAb.kkqNV8zqf4vA1JBkRnTJiIp+7SamMjDtz8VFODRsg==/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTU2Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS92MTAwMjMxL1dpbmRvd3MuemlwdTk6dGltZXN0YW1wdTEwOjIwMjItMDYtMjhl, remote: 100260/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQCG2yQNyXu3ovuUBNMEQiqx1vdo.FCMet9FoayFiIL89QIgXGRTU84nrcmLL4ud2j9ogrGt7ScmqaD97N.4rrtraXE=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTU2Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS92MTAwMjYwL1dpbmRvd3MuemlwdTk6dGltZXN0YW1wdTEwOjIwMjItMDctMjhl)
[7215:0810/114511.208858:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
The signature successfully was verified using the -p/--public-key="03eeedcd574708681afb3f02fb2aef7c643583089267d17af35e978ecaf2a1184e".
11:45:14.232 › config initialize called
11:45:14.678 › config initialize complete
11:45:14.678 › selected node: 9c-main-rpc-4.nine-chronicles.com:80, clients: 32
11:45:14.685 › main initializeApp call initializeRemoteHeadless
11:45:14.685 › Initialize remote headless. (win: function getTitle() { [native code] })
11:45:14.686 › Executing the remote headless server:
  9c-main-rpc-4.nine-chronicles.com/31238
11:45:14.687 › Register exit handler.
11:45:14.687 › initialize remote headless() finished.
11:45:14.784 › Created 'encounter different version' lockfile at  /home/lumomig/Downloads/artifact(1)/lockfile
11:45:14.784 › Cancelling initializeHeadless()
11:45:14.785 › initializeHeadless() cancelled.
11:45:14.785 › Killing standalone.
11:45:14.785 › Standalone is not alive.
11:45:14.786 › peerVersionExtra (hex): 647531363a57696e646f777342696e61727955726c7535363a68747470733a2f2f646f776e6c6f61642e6e696e652d6368726f6e69636c65732e636f6d2f763130303236302f57696e646f77732e7a697075393a74696d657374616d707531303a323032322d30372d323865
11:45:14.786 › peerVersionExtra (bytes): {
  '0': 100,
  '1': 117,
  '2': 49,
  '3': 54,
  '4': 58,
  '5': 87,
  '6': 105,
  '7': 110,
  '8': 100,
  '9': 111,
  '10': 119,
  '11': 115,
  '12': 66,
  '13': 105,
  '14': 110,
  '15': 97,
  '16': 114,
  '17': 121,
  '18': 85,
  '19': 114,
  '20': 108,
  '21': 117,
  '22': 53,
  '23': 54,
  '24': 58,
  '25': 104,
  '26': 116,
  '27': 116,
  '28': 112,
  '29': 115,
  '30': 58,
  '31': 47,
  '32': 47,
  '33': 100,
  '34': 111,
  '35': 119,
  '36': 110,
  '37': 108,
  '38': 111,
  '39': 97,
  '40': 100,
  '41': 46,
  '42': 110,
  '43': 105,
  '44': 110,
  '45': 101,
  '46': 45,
  '47': 99,
  '48': 104,
  '49': 114,
  '50': 111,
  '51': 110,
  '52': 105,
  '53': 99,
  '54': 108,
  '55': 101,
  '56': 115,
  '57': 46,
  '58': 99,
  '59': 111,
  '60': 109,
  '61': 47,
  '62': 118,
  '63': 49,
  '64': 48,
  '65': 48,
  '66': 50,
  '67': 54,
  '68': 48,
  '69': 47,
  '70': 87,
  '71': 105,
  '72': 110,
  '73': 100,
  '74': 111,
  '75': 119,
  '76': 115,
  '77': 46,
  '78': 122,
  '79': 105,
  '80': 112,
  '81': 117,
  '82': 57,
  '83': 58,
  '84': 116,
  '85': 105,
  '86': 109,
  '87': 101,
  '88': 115,
  '89': 116,
  '90': 97,
  '91': 109,
  '92': 112,
  '93': 117,
  '94': 49,
  '95': 48,
  '96': 58,
  '97': 50,
  '98': 48,
  '99': 50,
  '100': 50,
  '101': 45,
  '102': 48,
  '103': 55,
  '104': 45,
  '105': 50,
  '106': 56,
  '107': 101
}
11:45:14.792 › peerVersionExtra (decoded): {}
11:45:14.792 › macOSBinaryUrl:  null
11:45:14.793 › WindowsBinaryUrl:  https://download.nine-chronicles.com/v100260/Windows.zip
11:45:14.793 › Stop update process. Not support linux.
Key ID                               Address                                   
------------------------------------ ------------------------------------------
11:45:15.886 › 'encounter different version' event seems running already. Stop this flow.
```
![image](https://user-images.githubusercontent.com/6278999/183799096-752b11bf-994e-4b9a-8414-c56ceba8d1cd.png)

**Comment by Akamig** [comment]
Stale & Solved issue currently, closing.
