### ISSUE TITLE
Too many `differentApvEncounter` event

### ISSUE THREAD

**Issue by Atralupus** [planetarium/9c-launcher#1941]
Now, the APV version is v100301 but some peers send v100291
So `encounter different version` event continuously called from other peers

```
[2022-09-28 10:43:55.740] [error] (node:135192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2022-09-28 10:43:56.747] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2022-09-28 10:43:56.747] [error] Error: New player commit hash required
    at C:\Users\temp\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:426:51189
    at Array.forEach (<anonymous>)
    at C:\Users\temp\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:426:51155
    at Yi (C:\Users\temp\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:426:51444)
    at IpcMainImpl.<anonymous> (C:\Users\temp\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:426:65880)
    at IpcMainImpl.emit (node:events:527:28)
    at IpcMainImpl.emit (node:domain:475:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
[2022-09-28 10:43:56.748] [error] (node:135192) UnhandledPromiseRejectionWarning: Error: New player commit hash required
    at C:\Users\temp\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:426:51189
    at Array.forEach (<anonymous>)
    at C:\Users\temp\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:426:51155
    at Yi (C:\Users\temp\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:426:51444)
    at IpcMainImpl.<anonymous> (C:\Users\temp\AppData\Local\Programs\Nine Chronicles\resources\app\main.js:426:65880)
    at IpcMainImpl.emit (node:events:527:28)
    at IpcMainImpl.emit (node:domain:475:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
```

The situation itself is not huge, but... it's being called too many times.
We should reduce the event called.

**Comment by Atralupus** [comment]
hotfixed https://github.com/planetarium/9c-launcher/pull/1939
