### ISSUE TITLE
[error] TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by riemannulus** [planetarium/9c-launcher#364]
```
[2020-09-21 16:17:23.296] [warn] Could not connect to Sentry main process. Did you call init?
[2020-09-21 16:21:36.351] [error] TypeError: Cannot read property '0' of null
    at EventEmitter.i.send.i.sendSync (electron/js2c/renderer_init.js:74:326)
    at file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/render.4ab75a409285418740fb.js:144:9432417
    at Bh (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:126:456)
    at Dj (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:162:476)
    at unstable_runWithPriority (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react/umd/react.production.min.js:25:260)
    at Da (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:60:280)
    at xb (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:162:231)
    at Te (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:146:79)
    at file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:61:68
    at unstable_runWithPriority (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react/umd/react.production.min.js:25:260)
    at Da (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:60:280)
    at Pg (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:61:14)
    at ha (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:60:451)
    at Rh (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:147:88)
    at nd (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:175:208)
    at Object.I.render (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/vendor/react-dom/umd/react-dom.production.min.js:238:412)
    at Module.<anonymous> (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/render.4ab75a409285418740fb.js:150:62677)
    at i (file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/render.4ab75a409285418740fb.js:1:110)
    at file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/render.4ab75a409285418740fb.js:1:902
    at file:///C:/Users/INNER%20PEACE/Desktop/%ED%81%AC%EB%A1%9C%EB%8B%88%ED%81%B4%EA%B2%8C%EC%9E%84/resources/app/render.4ab75a409285418740fb.js:1:913
```

**Comment by Akamig** [comment]
non-reproducible bug and possibly fixed now. closing.
