### ISSUE TITLE
특정 컴퓨터에서 check-disk-space 모듈이 정상적으로 작동하지 않습니다.

### ISSUE THREAD

**Issue by limebell** [planetarium/9c-launcher#491]
```
[2020-12-14 11:28:04.007] [info] Initialize standalone. (win: [object BrowserWindow])
[2020-12-14 11:28:04.009] [info] Create directory for given blockchain path.
[2020-12-14 11:28:04.138] [warn] This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2020-12-14 11:28:04.139] [error] Error: Command failed: wmic logicaldisk get size,freespace,caption
����:

���� = ���񽺸� ����� �� ���ų� ���񽺿� �����Ǿ� ��� ������ ��ġ�� ���� ������ ���񽺸� ������ �� �����ϴ�.


    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2020-12-14 11:28:16.967] [info] Cancelling initializeStandalone()
[2020-12-14 11:28:16.968] [info] initializeStandalone() cancelled.
[2020-12-14 11:28:16.970] [info] Killing standalone.
[2020-12-14 11:28:16.971] [info] Standalone is not alive.
[2020-12-14 11:28:16.972] [info] Deleting blockchain store.
```

특정 컴퓨터에서 `check-disk-space` 모듈 내에서 [`wmic logicaldisk get size,freespace,caption` 을 부르는 부분](https://github.com/Alex-D/check-disk-space/blob/c160ab82677bcb81464f7d551252bf8f8823eb83/index.js#L93)이 문제인 것으로 보입니다.

![image](https://user-images.githubusercontent.com/5073795/102733980-02664b80-4382-11eb-984f-f5d96ad6f1c3.png)

우선 해당 구문에 대한 에러 처리를 추가해 이 이슈가 발생하더라도 먼저 정상적으로 실행이 될 수 있게 하고, 후속 작업으로 문제를 완전히 해결해야 할 것 같습니다.

- [x] 해당 구문 `try~ catch` 블록으로 감싸기
- [ ] 해당 상황 해결하기

**Comment by BasixKOR** [comment]
메시지를 고려하면 WMI 서비스가 시작되지 않도록 패치된 경우로 추정됩니다. `net start "Windows Management Instrumentation"` 등으로 WMI를 강제로 시동한 뒤 실행하도록 `check-disk-space`를 패치하여 PR을 보내보고, 안 되면 별도로 포크를 관리해야 할 것 같습니다.
